version: '3.4'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  storage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  adminpanel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

